# Generated by Django 4.1.5 on 2023-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedngo',
            name='cause',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='country',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='description',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='domain',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='email',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='gross_income',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='image',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='mission',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='organization_address',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='phone',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='registration_date_day',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='registration_date_month',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='registration_date_year',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='state',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='urls_scraped',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedngo',
            name='website',
            field=models.JSONField(null=True),
        ),
    ]
