# Generated by Django 4.1.5 on 2023-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0002_alter_mergedngo_cause_alter_mergedngo_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedngo',
            name='organization_name',
            field=models.JSONField(null=True),
        ),
    ]
