# Generated by Django 4.1.5 on 2023-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0004_uniquengo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquengo',
            name='pledge_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
