# Generated by Django 4.1.5 on 2023-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0005_uniquengo_pledge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquengo',
            name='merged',
        ),
        migrations.RemoveField(
            model_name='uniquengo',
            name='pledge_id',
        ),
        migrations.AddField(
            model_name='uniquengo',
            name='has_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniquengo',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
