# Generated by Django 4.1.5 on 2023-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0006_remove_uniquengo_merged_remove_uniquengo_pledge_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniquengo',
            unique_together=set(),
        ),
    ]
