# Generated by Django 4.1.5 on 2023-05-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0007_alter_uniquengo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniquengo',
            unique_together={('govt_reg_number', 'govt_reg_number_type')},
        ),
        migrations.RemoveField(
            model_name='uniquengo',
            name='has_merged',
        ),
        migrations.RemoveField(
            model_name='uniquengo',
            name='locked',
        ),
    ]
