# Generated by Django 4.1.5 on 2023-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGivingIndexedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('scraped_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
