# Generated by Django 4.1.5 on 2023-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving', '0002_globalgivingngo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalgivingngo',
            name='id',
        ),
        migrations.AlterField(
            model_name='globalgivingngo',
            name='organization_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
