# Generated by Django 4.1.5 on 2023-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving', '0003_remove_globalgivingngo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgivingindexedurl',
            name='trial',
            field=models.IntegerField(default=0),
        ),
    ]
