# Generated by Django 4.1.5 on 2023-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving', '0004_globalgivingindexedurl_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgivingngo',
            name='organization_address',
            field=models.TextField(null=True),
        ),
    ]
