# Generated by Django 4.1.5 on 2023-04-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving', '0006_ngo_ngo_global_givi_organiz_852e53_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2GlobalGivingIndexedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('scraped_on', models.DateTimeField(null=True)),
                ('trial', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalGivingNGO',
        ),
        migrations.RemoveIndex(
            model_name='ngo',
            name='global_givi_organiz_852e53_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ngo',
            unique_together={('organization_name', 'description')},
        ),
    ]
