# Generated by Django 4.1.5 on 2023-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving', '0008_alter_ngo_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('scraped_on', models.DateTimeField(null=True)),
                ('trial', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='V2GlobalGivingIndexedUrl',
        ),
    ]
