# Generated by Django 4.1.5 on 2023-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving', '0010_delete_v2url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
