# Generated by Django 4.1.5 on 2023-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0003_ngo_guidestarindexedurl_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestarindexedurl',
            name='govt_reg_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guidestarindexedurl',
            name='govt_reg_number_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guidestarindexedurl',
            name='organization_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guidestarindexedurl',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
