# Generated by Django 4.1.5 on 2023-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0005_errorpage_lastpage_alter_ngo_govt_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='organization_address',
            field=models.TextField(null=True),
        ),
    ]
