# Generated by Django 4.1.5 on 2023-04-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0006_alter_ngo_organization_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={'ordering': ['organization_name', 'state']},
        ),
    ]
