# Generated by Django 4.1.5 on 2023-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0007_alter_ngo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpage',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lastpage',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
