# Generated by Django 4.1.5 on 2023-04-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0008_errorpage_city_lastpage_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={},
        ),
    ]
