# Generated by Django 4.1.5 on 2023-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0009_alter_ngo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
