# Generated by Django 4.1.5 on 2023-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0010_failedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedfiles',
            name='file_name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
