# Generated by Django 4.1.5 on 2023-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0012_alter_failedfiles_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
