# Generated by Django 4.1.5 on 2023-04-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0013_ngo_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
