# Generated by Django 4.1.5 on 2023-04-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0015_ngo_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='updated',
        ),
    ]
