# Generated by Django 4.1.5 on 2023-04-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0016_remove_ngo_locked_remove_ngo_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
