# Generated by Django 4.1.5 on 2023-04-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidestar_app', '0017_ngo_locked_ngo_resolved_ngo_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='updated_on',
        ),
    ]
