# Generated by Django 4.1.5 on 2023-01-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0002_crawlcursor_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgeindexedurl',
            name='crawler',
        ),
    ]
