# Generated by Django 4.1.5 on 2023-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0006_alter_ngo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgeindexedurl',
            name='trial',
            field=models.IntegerField(default=0),
        ),
    ]
