# Generated by Django 4.1.5 on 2023-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0007_pledgeindexedurl_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlcursor',
            name='id',
        ),
        migrations.AlterField(
            model_name='crawlcursor',
            name='app',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
