# Generated by Django 4.1.5 on 2023-03-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0008_remove_crawlcursor_id_alter_crawlcursor_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(default='education', max_length=200, unique=True)),
            ],
        ),
    ]
