# Generated by Django 4.1.5 on 2023-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0009_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('cause', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
