# Generated by Django 4.1.5 on 2023-04-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0010_lastpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='ngo',
            unique_together={('organization_name', 'state')},
        ),
    ]
