# Generated by Django 4.1.5 on 2023-04-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0012_alter_ngo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={},
        ),
    ]
