# Generated by Django 4.1.5 on 2023-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0013_alter_ngo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
