# Generated by Django 4.1.5 on 2023-05-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0015_remove_ngo_locked_remove_ngo_resolved_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ngo',
            unique_together=set(),
        ),
    ]
