# Generated by Django 4.1.5 on 2023-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_navigator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1)),
                ('error', models.TextField(null=True)),
            ],
        ),
    ]
