# Generated by Django 4.1.5 on 2023-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_navigator', '0002_failedpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedpages',
            name='id',
        ),
        migrations.AlterField(
            model_name='failedpages',
            name='page',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
