# Generated by Django 4.1.5 on 2023-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_navigator', '0003_remove_failedpages_id_alter_failedpages_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedpages',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='failedpages',
            name='trial',
            field=models.IntegerField(default=0),
        ),
    ]
