# Generated by Django 4.1.5 on 2023-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_navigator', '0004_failedpages_locked_failedpages_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1)),
                ('state', models.CharField(max_length=200)),
                ('cause', models.CharField(max_length=200)),
            ],
        ),
    ]
