# Generated by Django 4.1.5 on 2023-04-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_navigator', '0006_alter_ngo_options_alter_ngo_govt_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name_plural': 'NGOs'},
        ),
    ]
