states = [
        'AK',
        'AL',
        'AR',
        'AS',
        'AZ',
        'CA',
        'CO',
        'CT',
        'DC',
        'DE',
        'FL',
        'GA',
        'GU',
        'HI',
        'IA',
        'ID',
        'IL',
        'IN',
        'KS',
        'KY',
        'LA',
        'MA',
        'MD',
        'ME',
        'MI',
        'MN',
        'MO',
        'MP',
        'MS',
        'MT',
        'NA',
        'NC',
        'ND',
        'NE',
        'NH',
        'NJ',
        'NM',
        'NV',
        'NY',
        'OH',
        'OK',
        'OR',
        'PA',
        'PR',
        'RI',
        'SC',
        'SD',
        'TN',
        'TX',
        'UT',
        'VA',
        'VI',
        'VT',
        'WA',
        'WI',
        'WV',
        'WY',        
    ]

causes = ["Arts and culture", 
           "Education", 
           "Environment", 
           "Health", 
           "Technology", 
           "Forensic science", 
           "Public safety", 
           "Public affairs", 
           "Agriculture", 
           "fishing and forestry", 
           "Religion", 
           "Sports and recreation", 
           "Human rights", 
           "Human services", 
           "International relations", 
           "Unknown or not classified"           
           ]

beacons = [
    "Leadership & Adaptability",
    "Accountability & Finance",
    "Impact & Results",
    "Culture & Community",
]

   