def short_region_name(full_name):
        states = {
            'Alaska': 'AK',
            'Alabama': 'AL',
            'Arkansas': 'AR',
            'American Samoa': 'AS',
            'Arizona': 'AZ',
            'California': 'CA',
            'Colorado': 'CO',
            'Connecticut': 'CT',
            'District of Columbia': 'DC',
            'Delaware': 'DE',
            'Florida': 'FL',
            'Georgia': 'GA',
            'Guam': 'GU',
            'Hawaii': 'HI',
            'Iowa': 'IA',
            'Idaho': 'ID',
            'Illinois': 'IL',
            'Indiana': 'IN',
            'Kansas': 'KS',
            'Kentucky': 'KY',
            'Louisiana': 'LA',
            'Massachusetts': 'MA',
            'Maryland': 'MD',
            'Maine': 'ME',
            'Michigan': 'MI',
            'Minnesota': 'MN',
            'Missouri': 'MO',
            'Northern Mariana Islands': 'MP',
            'Mississippi': 'MS',
            'Montana': 'MT',
            'National': 'NA',
            'North Carolina': 'NC',
            'North Dakota': 'ND',
            'Nebraska': 'NE',
            'New Hampshire': 'NH',
            'New Jersey': 'NJ',
            'New Mexico': 'NM',
            'Nevada': 'NV',
            'New York': 'NY',
            'Ohio': 'OH',
            'Oklahoma': 'OK',
            'Oregon': 'OR',
            'Pennsylvania': 'PA',
            'Puerto Rico': 'PR',
            'Rhode Island': 'RI',
            'South Carolina': 'SC',
            'South Dakota': 'SD',
            'Tennessee': 'TN',
            'Texas': 'TX',
            'Utah': 'UT',
            'Virginia': 'VA',
            'Virgin Islands': 'VI',
            'Vermont': 'VT',
            'Washington': 'WA',
            'Wisconsin': 'WI',
            'West Virginia': 'WV',
            'Wyoming': 'WY'
        }
        state_name = states.get(full_name)
        return full_name if state_name is None else state_name
    


                 
sub_causes = [
    "animals-pets",
    "animals-veterinary-services",
    "animals-wildlife",
    "art-museums",
    "art-performing-arts",
    "art-visual-arts",
    "disaster-relief-natural-disasters",
    "disaster-relief-refugee-services",
    "education-colleges-and-universities",
    "education-educational-programs",
    "education-k-12",
    "education-preschool",
    "education-sororities-fraternities",
    "education-steam",
    "environment-climate-change",
    "environment-nature-conservation",
    "environment-ocean",
    "health-cancer",
    "health-coronavirus",
    "health-disease",
    "health-disorders",
    "health-drug-rehabilitation",
    "health-hiv-aids",
    "health-hospitals",
    "health-medical-research",
    "health-mental-health",
    "health-women-s-health",
    "justice-criminal-justice",
    "justice-domestic-violence",
    "justice-lgbtq",
    "justice-racial-justice",
    "justice-women-girls",
    "science-science-research",
    "science-space-exploration",
    "society-children-family",
    "society-clean-water",
    "society-cultural-ethnic-centers",
    "society-employment",
    "society-food-nutrition",
    "society-housing",
    "society-military-veterans",
    "society-religion",
    "society-senior-care",
    "society-sports-and-recreation",
    "society-youth-development"
]