# Generated by Django 4.1.5 on 2023-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving_india', '0002_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='ngo',
            unique_together={('govt_reg_number', 'govt_reg_number_type')},
        ),
    ]
