# Generated by Django 4.1.5 on 2023-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_giving_india', '0003_alter_ngo_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='organization_address',
            field=models.TextField(null=True),
        ),
    ]
