# Generated by Django 4.1.5 on 2023-02-25 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('irs_app', '0002_irsindexedurl_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLUrlIndexer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('scraped_on', models.DateTimeField(null=True)),
                ('trial', models.IntegerField(default=0)),
                ('file_name', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
