# Generated by Django 4.1.5 on 2023-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irs_app', '0003_xmlurlindexer'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlurlindexer',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
