# Generated by Django 4.1.5 on 2023-03-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irs_app', '0005_xml_ngo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XML_NGO',
        ),
    ]
