# Generated by Django 4.1.5 on 2023-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irs_app', '0008_alter_zip_ngo_govt_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='organization_address',
            field=models.CharField(max_length=500),
        ),
    ]
