# Generated by Django 4.1.5 on 2023-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irs_app', '0010_ngo_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo_v2',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
    ]
